### ISSUE TITLE
Canadarm hosting

### ISSUE THREAD

**Issue by garrypolley** [cerner/canadarm#1]
We need to figure out a strategy for hosting canadarm.  It's a hassle to ask people to copy paste the source. If we had it on a place like cdnjs that would be great.

**Comment by garrypolley** [comment]
Looking at some options for a CDN. Since this library is not super popular yet the easiest one I could find was here:  https://github.com/jsdelivr/jsdelivr/pull/5161

Hopefully they'll except the library.

**Comment by garrypolley** [comment]
It appears we will soon have at least one CDN: 

https://github.com/jsdelivr/jsdelivr/pull/5179

**Comment by garrypolley** [comment]
See the hosted file here: 

http://cdn.jsdelivr.net/canadarm/1.0.0/canadarm.min.js

**Comment by garrypolley** [comment]
See the original post on jsdelivr: https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/

**Comment by garrypolley** [comment]
Note to those following this, we need to update the documentation to include the CDN we are hosted on.

**Comment by southpawlife** [comment]
This can now be closed, as that documentation was merged last year. :smile:

**Comment by garrypolley** [comment]
Thanks!  @southpawlife
