### ISSUE TITLE
Custom log breaks in node context

### ISSUE THREAD

**Issue by JohnPhoto** [cerner/canadarm#20]
I'm building an isomorphic application which executes the same code both on a node-server and in the browser.
When I manually call `Canadarm.warn('test')` in the "node-context" I get the following error:

```
project/node_modules/canadarm/build/canadarm.js:472
    var scripts = window.document.getElementsByTagName('script');
                                   ^

TypeError: window.document.getElementsByTagName is not a function
    at standardLogAppender (project/node_modules/canadarm/build/canadarm.js:472:35)
    at gatherErrors (project/node_modules/canadarm/build/canadarm.js:278:18)
    at Object.warn (project/node_modules/canadarm/build/canadarm.js:337:15)
    at Object.module.exports.Object.defineProperty.value (project/dist/server/index.js:1115:19)
    at __webpack_require__ (project/dist/server/index.js:508:30)
    at fn (project/dist/server/index.js:39:20)
    at Object.<anonymous> (project/dist/server/index.js:967:13)
    at __webpack_require__ (project/dist/server/index.js:508:30)
    at fn (project/dist/server/index.js:39:20)
    at Object.module.exports.Object.defineProperty.value (project/dist/server/index.js:926:14)
error: Forever detected script exited with code: 1
``` 

The code in Canadarm which does this is:

```
  // If stack is not defined we are in a browser that does not fully support our logging.
  // Or one of our custom loggers was called, e.g. Logger.debug('message').
  if (exception === undefined || exception === null || exception.stack === null) {
    var scripts = window.document.getElementsByTagName('script');
    scriptURL = (window.document.currentScript || scripts[scripts.length - 1]).src;

  }
```

Is Canadarm supposed to work with my kind of setup?

**Comment by garrypolley** [comment]
We should fix that. I'm out of town for a few weeks but can look at it
around the 15th of April. Ideally it would check and ignore in a node
context.

**Comment by gneatgeek** [comment]
@garrypolley beat me to it.  @JohnPhoto, would you be interested and contributing the fix for this issue?

**Comment by JohnPhoto** [comment]
I can fix the fix.
Something in the concepts of the following right?
```
if(!window.document.getElementsByTagName){
  // This is not the stuff you're looking for, I'll just gracefully "return".
}
```

**Comment by JohnPhoto** [comment]
I have tested the output from my PR in my codebase and it works beautifully.
`scriptURL: '?' `

**Comment by mhemesath** [comment]
Would a simpler approach be to just detect the global variable identifying the current file in Node and if not present fallback onto looking up the script? 

* https://nodejs.org/api/globals.html#globals_filename
* https://nodejs.org/api/globals.html#globals_dirname

**Comment by garrypolley** [comment]
I would prefer these approaches.

**Comment by mhemesath** [comment]
Garry I moved my comment to the pull request... can you respond there?
