### ISSUE TITLE
handle recaptcha api errors gracefully

### ISSUE THREAD

**Issue by roger-link** [cerner/canadarm#26]
Please fill out the below template as best you can.
--------------------------------------------------------

### Description of Issue
We're currently running into issues with the recaptcha api. It seems that an issue with the recaptcha api prevented the captcha from rendering on the page. 

Here's the error seen in the browser:
```
canadarm.js:597 Uncaught TypeError: Cannot set property '_wrapper' of null
    at _watchFn (canadarm.js:597)
    at Object.Canadarm.watch (canadarm.js:615)
    at window.EventTarget.addEventListener (canadarm.js:767)
    at recaptcha__en.js:39
    at recaptcha__en.js:39
    at recaptcha__en.js:411
canadarm.js:471 Uncaught TypeError: Cannot read property 'stack' of null
    at standardLogAppender (canadarm.js:471)
    at gatherErrors (canadarm.js:278)
    at Object.fatal (canadarm.js:337)
    at _onError (canadarm.js:713)
```

We have requested a fix to google's recaptcha, but would also like to see a fix to canadarm. This fix would allow issues with the recaptcha api to pass through canadarm and not affect the application. 

https://groups.google.com/forum/#!topic/recaptcha/FPkQ8VFY0zI
https://github.com/google/recaptcha/issues/166

### Steps to Reproduce the Issue
1. Navigate to: https://muhealthe.iqhealth.com/self-enroll/
1. Inspect browser console.

### Expected Outcomes
- Logging does not break if there is an issue with Googles recaptcha api.

**Comment by garrypolley** [comment]
If I had to guess I think this is an issue with how Canadarm "wraps" event handling. 

https://github.com/cerner/canadarm/blob/master/build/canadarm.js#L792-L805

Specifically, some how the "watch" function is not getting set, or is getting unset during execution of this code. 

https://github.com/cerner/canadarm/blob/master/build/canadarm.js#L612-L629

I'm going to need a way to reproduce this in a reliable way, otherwise I can keep guessing. 😺

**Comment by roger-link** [comment]
Sorry. We just fixed it in prod.

https://muhealthe.stagingiqhealth.com/self-enroll/

**Comment by garrypolley** [comment]
Looking at the includes, it is a requirement that Canadarm comes first in the `<head>`.  

The readme makes it sound like that's optional, but it isn't. Especially if the item included before it has an error. 
<img width="921" alt="screen shot 2017-06-19 at 2 24 01 pm" src="https://user-images.githubusercontent.com/992175/27302030-f7350f72-54fa-11e7-88b3-f1735610ff09.png">

The recaptcha code needs to be included after Canadarm. I'd be curious to see what happens after that.

**Comment by roger-link** [comment]
I'll rearrange and get back with you. Thanks!
